#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#description: connect the UART port of user's board by telnet

. check_board

# Usage information
usage()
{
    echo "Usage: board_connect [Num]"
    echo "    -h     : Display this information"
    echo "    Num    : To use the specified board assigned to user, Num is an interger board index which must be greater than 0, default to use No.1 board."
	exit
}

declare board_using=0
declare board_user="no user"
using_check()
{
 	current=`ps -o ruser=userForLongName -e -o pid,ppid,c,stime,tty,time,cmd|grep telnet |grep -w $1|cut -d " " -f1`
 	psid=`ps -o ruser=userForLongName -e -o pid,ppid,c,stime,tty,time,cmd |grep -w $1|awk '{print $2}'`
	current=`echo $current|cut -d "+" -f1`
	echo "psid is $psid"
	if [ "$current" = "" ];then
        	board_using=0
    	else
       		board_using=1
		board_user="$current"
    	fi
}

check_neccessary()
{
    BAK_PATH=$ftp_dir/$ftp_bak

    if [ x"$BOARDTYPE" = x"D01" ];then
        IMG=$img_d01
        DTB=$dtb_d01
    else
        IMG=$img_d02
        DTB=$dtb_d02
    fi

    CPIO=$mini_rootfs

	if [ ! -f ~/ftp/$IMG ] ;then
		cp $BAK_PATH/$IMG ~/ftp/
	fi 
	if [ ! -f ~/ftp/$DTB ];then
		cp $BAK_PATH/$DTB ~/ftp/
	fi
	if [ ! -f ~/ftp/$CPIO ];then
		cp $BAK_PATH/$CPIO ~/ftp/	
	fi
	
    cfgfile="${DEFCFG}.${BOARDNO}"
	if [ ! -f $cfgfile ]; then
		gencfg.sh $BOARDNO
	fi
    cp ${cfgfile} $GRUBFILE
}

function show_confirm()
{
	read -n1 -p "Do you want to kill it and try a new session [Y/N]?" answer
	case $answer in
	Y | y)
     echo  -e "\n fine ,continue"
	;;
	N | n)
    echo -e "\n ok,good bye"
	exit 0
	;;
	*)
 	echo -e  "\n Sorry! Error choice"
	exit 0
	;;
	esac
}

connect()
{
     using_check $1
     if [ $board_using = 1 ];then
         usinginfo=`grep -w "$board_user:" $USERCFG`
         mail_addr=${usinginfo#*email=}
         mail_addr=${mail_addr%%,*}
         mail_user=${usinginfo%%:*}
     	if [ "$USERNAME" = "$mail_user" ];then
     		echo "You are using another session connected to the board"
     		show_confirm
     		echo "kill the ps $psid"
     		kill $psid
     	else
         	echo "$mail_addr is using the board on $2"
         	echo "if you really want to use it, please contact with him"
        		exit 1
     	fi
    fi

    check_neccessary
	echo -e "\033[0m"
	echo -e "\033[32mConnected to board: No=$BOARDIDX, type=$BOARDTYPE, port=$PORT, power=$POWER $OUTLET, grub=$GRUBFILE.\033[0m"
    telnet localhost $1
    
    exit 0
}

if [ x"$#" = x"1" -a x"$1" = x"-h" ]; then
    usage
    exit
fi

if [ $# -gt 0 ]; then
    showhelp=1
    if [ $# = 1 ]; then
        if [ "$1" -gt 0 ] 2>/dev/null ; then 
            showhelp=0 
        fi
    fi

    if [ $showhelp = 1 ];then
        usage
        exit
    fi
fi

connect $PORT
