#!/bin/bash
#author: Justin Zhao
#date 23/11/2015
#description: list all boards possessed by user


USERCFG=/etc/boardlab/users.cfg
USERNAME=`whoami`


if [ x"boardslist" = x"$1" ]; then
    echo "${USERNAME} possessed boards list:"
    echo "Idx: Board No -> Shared Users"
    idx=1
    while [ true ]
    do
	boardno=`echo ${boards%%,*} | cut -d " " -f$idx`
	if [ x"" = x"$boardno" ]; then
		exit 0
	fi
	shared=`grep -E "boards=.*\b${boardno}\b" $USERCFG | grep -v "${USERNAME}:" | cut -d "," -f1 | sed "s/email=//g" | tr '\n' ";"|sed "s/;/; /g"`
	if [ x"" = x"$shared" ]; then
		echo "${idx}  : ${boardno}"
	else
		echo "${idx}  : ${boardno} -> ${shared}"
	fi
	let idx=$idx+1
    done
fi
