#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#description: connect the UART port of user's board by telnet

. check_board
source connect_op



# check and connect board
connect_board_op()
{
    check_use_status "$BOARDNUM" "board_connect"
    if [ "$current" = "" ];then
	connect_board_op_action
    else
        usinginfo=`grep -w "$current:" $USERCFG`
        mail_addr=${usinginfo#*email=}
        mail_addr=${mail_addr%%,*}
        mail_user=${usinginfo%%:*}
        if [ "$USERNAME" = "$mail_user" ];then
            echo "You are using another session connected to the board"
     	    show_confirm
     	    echo "kill the ps $psid"
     	    kill $psid
            if [ "$SERIALTYPE" = "BMC" ]; then
                echo "please wait 60 second,then connect again" 
                echo " "
            elif [ "$SERIALTYPE" = "BMC" ]; then
		connect_board_op_action
            fi
     	else
            echo "$mail_addr is using the board "
            echo "if you really want to use it, please contact with him"
            exit 1
        fi
    fi

}


# if the cmd board_connet not with parameter,$#=0:the default operation is connect board
# if the parameter num=1: the may three case, one is  "board_connect -h" show the usage, the second one is "board_connec num" to connect board num.(if the num is wrong at check_board script will prompt)
# the third one is: other all wrong parameter case
# if more than one parameter,then show usage
if [ $# = 0 ]; then
    connect_board_op
elif [ x"$#" = x"1" ]; then
    if [ x"$1" = x"-h" ]; then
        usage
        exit
    elif [ $1 -gt 0 ]; then
        connect_board_op
    else 
	usage
        exit
    fi
elif  [ $# > 1  ]; then
    usage
    exit
fi





