#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#Description: this is the pdu control script


POWER_CMD=ap7921-control

# take power action,
# the parameter is pud_ip, pdu outlet and operation on:1,off=2,reboot=3
# include d01 d02 1610 and othe other boards without BMC
board_op_power_pdu()
{
    OPER=3
    case $1 in 
    "on")
	OPER=1
	;;
    "off")
	OPER=2
	;;
    "reboot")
	OPER=3
	;;
    *)
	usage
    exit
 	;;
    esac
    # power on board
    $POWER_CMD $PDU_HOST $OUTLET $OPER
    echo ""  
}




# power option:  boards wiht BMC,such as d03
# 
board_op_power_bmc()
{
    # action on power
    case $1 in 
    "on" | "off" )
         ipmitool -H $BMCIP -I $IPMI_INTERFACE -U $ACCOUNT -P $PASSWORD $IPMI_POWER_CMD $1 
         ;;
    "reboot")
         ipmitool -H $BMCIP -I $IPMI_INTERFACE -U $ACCOUNT -P $PASSWORD $IPMI_POWER_CMD off 
         sleep 3
         ipmitool -H $BMCIP -I $IPMI_INTERFACE -U $ACCOUNT -P $PASSWORD $IPMI_POWER_CMD on 
         ;;
    *)
         usage
         ;;
    esac
}


# check and get pdu config parameter
check_pdu_config()
{
    pdu_serial=`grep -w "$CONFIGINFO:" $PDUCFG`
    if [ $? -ne 0 ]; then
	# Check whether the power controller is deployed
	echo "$CONFIGINFO not config or configure is wrong, please touch lab Manager"
	exit 1
    fi
# this parameter will be used at board_connet
#    PORT=${pdu_serial#*ser2net=}
#    PORT=${PORT%%,*}
#    MANAGER_SERVER_IP=${pdu_serial#*ser2net=}
#    MANAGER_SERVER_IP=${MANAGER_SERVER_IP%%,*}    

    POWER=${pdu_serial#*power=}
    POWER=${POWER%%,*}
    OUTLET=`echo $POWER | cut -d " " -f2`
    POWER=`echo $POWER | cut -d " " -f1`
	
    POWER_CMD=ap7921-control
    # Get the power controller information
    powerinfo=`grep -w "$POWER:" $PDUCFG`
    PDU_HOST=${powerinfo#*ip=}
    PDU_HOST=${PDU_HOST%%,*}
}


# check and get bmc config parameter
check_bmc_config()
{
   bmcinfo=`grep -w "$CONFIGINFO:" $BMCCFG`
   if [ $? -ne 0 ];then
	# Check whether the power controller is deployed
        echo "$CONFIGINFO is not config or config is wrong, please touch lab Manager."
        exit 1
    fi
    BMCIP=${bmcinfo#*bmcip=}
    BMCIP=${BMCIP%%,*}
 
# this parameter will be used at board_connet
#    IPMI_INTERFACE=${bmcinfo#*ipmi_interface=}
#    IPMI_INTERFACE=${IPMI_INTERFACE%%,*}

    IPMI_SERIAL_CMD=${bmcinfo#*ipmi_serial_cmd=}
    IPMI_SERIAL_CMD=${IPMI_SERIAL_CMD%%,*}

    IPMI_POWER_CMD=${bmcinfo#*ipmi_power_cmd=}
    IPMI_POWER_CMD=${IPMI_POWER_CMD%%,*}

    ACCOUNT=${bmcinfo#*account=}
    ACCOUNT=${ACCOUNT%%,*}

    PASSWORD=${bmcinfo#*password=}
    PASSWORD=${PASSWORD%%,*}
}



# according to SERIALTYPE and POWERTYPE to take different function
#
board_op_power()
{
    if [ "$SERIALTYPE" = "ipmi" -a "$POWERTYPE" = "BMC" ]; then
       check_bmc_config
       board_op_power_bmc $1

    elif [ "$SERIALTYPE" = "telnet" -a "$POWERTYPE" = "PDU" ]; then
        check_pdu_config
	board_op_power_pdu $1
    #elif ...
    fi
}






