#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#Description: this is the pdu control script
#

. check_board
POWER_CMD=ap7921-control

# Get the power controller information
powerinfo=`grep -w "$POWER:" $BOARDCFG`
PDU_HOST=${powerinfo#*ip=}
PDU_HOST=${PDU_HOST%%,*}

usage()
{
    echo "Usage: board_reboot [Num] [on|off|reboot]"
    echo "To power on, off or reboot specify boards, default to reboot board1 without any parameters!"
    echo "    Num:            To operate the specified board assigned to user, Num is an interger board index which must be greater than 0, default to operate board1."
    echo "    on|off|reboot:  To specify a power operation, default to reboot."
    exit 0
} 

# include d01 d02 1610 and othe other boards without BMC
board_op_other()
{
	OPER=3
	case $1 in 
	"on")
		OPER=1
		;;
	"off")
		OPER=2
		;;
	"reboot")
		OPER=3
		;;
	*)
		usage
        exit
		;;
	esac

    # Check the whether the board is being used, and send the operation command
    current=`ps -o ruser=userForLongName -e -o pid,ppid,c,stime,tty,time,cmd | grep telnet | grep $PORT | cut -d " " -f1`
    current=`echo $current|cut -d "+" -f1`
    if [ "$current" = "" ];then
	    $POWER_CMD $PDU_HOST $OUTLET $OPER
		echo ""
    else
        current_user=`grep -w $current $USERCFG|cut -d ":" -f1`
        if [ "$current_user" = "$USERNAME" ];then
	        $POWER_CMD $PDU_HOST $OUTLET $OPER
			echo ""
        else
            email=`grep -w $current $USERCFG`
            email=${email#*email=}
            email=${email%%,*}
            echo "              ********WARNING********"
            echo "  $email is using the board on $PORT"
            echo "  Please wait until he/she  finishes the work"
            echo "  Or you can contact with him by email."
        fi
    fi
   exit 0
}

# power option of d03 and other boards wiht BMC: on off reboot
board_op_d03()
{
# action on power
if [ $BOARDTYPE = "D03" ]; then
	# include d03 and othe boards with BMC
	case $1 in 
	"on" | "off" )
	     ipmitool -H $BMCIP -I lanplus -U "root" -P "Huawei12#$" chassis $1 
	     ;;
	"reboot")
	     ipmitool -H $BMCIP -I lanplus -U "root" -P "Huawei12#$" chassis power off 
	     sleep 3
	     ipmitool -H $BMCIP -I lanplus -U "root" -P "Huawei12#$" chassis power on 
	;;
	*)
	     usage
             ;;
	esac
	exit
fi
}


# option which board,and operation it on power
board_op()
{
    if [ "$BOARDTYPE" = "D03" ]; then
        board_op_d03 $1
    else
	board_op_other $1
    fi
}


# action on power
if [ $# = 2 ]; then
	if [ "$1" -gt 0 ] 2>/dev/null ; then
	 board_op $2
	fi
	exit
fi


# more then 2 input parameter
if [ $# -gt 1 ]; then
    	usage
        exit
fi

#
if [ $# = 1 ]; then
	if [ "$1" -gt 0 ] 2>/dev/null ; then
           	 board_op reboot
        else
            	case $1 in
            	"on"|"off"|"reboot")
                board_op $1
                ;;
            	*)
                usage
                ;;
            	esac
       	 fi
         exit
fi


#default to reboot board1
board_op reboot



