#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#description: connect the UART port of user's board by telnet

USERCFG=/etc/boardlab/users.cfg
USERLOG=/var/log/login.log
BOARDCFG=/etc/boardlab/boards.cfg
POWERCFG=/etc/boardlab/power.cfg
SERIALCFG=/etc/boardlab/serial.cfg
LABCFG=/etc/boardlab/boardlab.cfg

USERNAME=`whoami`
. $LABCFG

# Check whether user in permit list
grep -w "$USERNAME:" $USERCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "You are not permited to use the board in OpenLab."
    exit 1
fi

# Get the board index
BOARDIDX=1
if [ $# -gt 0 ]; then
    if [ "$1" -gt 0 ] 2>/dev/null ; then
        BOARDIDX=$1
    fi
fi

userinfo=`grep -w "$USERNAME:" $USERCFG`
boards=${userinfo#*boards=}

BOARDIDX=`echo ${boards%%,*} | cut -d " " -f$BOARDIDX`
if [ x"" = x"$BOARDIDX" ]; then
    echo "Error board index!"
    exit 1
fi

# Check whether the board is deployed
grep -w "BOARD$BOARDIDX:" $BOARDCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "Board$BOARDIDX is not deployed into Open Lab, please touch the Lab. manager."
    exit 1
fi


# Get the email of user
#eval PORT=$((PORT$index))
EMAIL=${userinfo#*email=}
EMAIL=${EMAIL%%,*}

# Get the board information
boardinfo=`grep -w "BOARD$BOARDIDX:" $BOARDCFG`
BOARDTYPE=${boardinfo#*boardtype=}
BOARDTYPE=${BOARDTYPE%%,*}

SERIALTYPE=${boardinfo#*serialtype=}
SERIALTYPE=${SERIALTYPE%%,*}

SERIALINFO=${boardinfo#*serialinfo=}
SERIALINFO=${SERIALINFO%%,*}

POWERTYPE=${boardinfo#*powertype=}
POWERTYPE=${POWERTYPE%%,*}

POWERINFO=${boardinfo#*powerinfo=}
POWERINFO=${POWERINFO%%,*}
POWER=`echo "$POWERINFO" | cut -d " " -f1`
OUTLET=`echo "$POWERINFO" | cut -d " " -f2`


MAC=${boardinfo#*mac=}
MAC=${MAC%%,*}
GRUBFILE=$ftp_dir/$grub_prefix-$MAC


check_pud_serial_config()
{
    pdu_ip=`grep -w "$POWER:" $POWERCFG`
    if [ $? -ne 0 ]; then
	# Check whether the power controller is deployed
	echo "$POWERINFO not config or configure is wrong, please touch lab Manager"
	exit 1
    fi
    POWER_CMD=ap7921-control
    PDU_HOST=${pdu_ip#*ip=}
    PDU_HOST=${PDU_HOST%%,}    
   
    serial_info=`grep -w "$SERIALINFO:" $SERIALCFG`
    if [ $? -ne 0 ]; then
	# Check whether the power controller is deployed
	echo "$SERIALINFO not config or configure is wrong, please touch lab Manager"
	exit 1
    fi
    MANAGER_SERVER_IP=${serial_info#*manager_server_ip=}
    MANAGER_SERVER_IP=`echo $MANAGER_SERVER_IP | cut -d "," -f1`

    PORT=${serial_info#*port=}
    PORT=${PORT%%,}
    
}


check_bmc_config()
{
   bmcinfo=`grep -w "$POWER:" $POWERCFG`
   if [ $? -ne 0 ];then
	# Check whether the power controller is deployed
        echo "$POWERINFO is not config or config is wrong, please touch lab Manager."
        exit 1
    fi
    BMCIP=${bmcinfo#*bmcip=}
    BMCIP=${BMCIP%%,*}
 
    IPMI_INTERFACE=${bmcinfo#*ipmi_interface=}
    IPMI_INTERFACE=${IPMI_INTERFACE%%,*}

    IPMI_SERIAL_CMD=${bmcinfo#*ipmi_serial_cmd=}
    IPMI_SERIAL_CMD=${IPMI_SERIAL_CMD%%,*}

    IPMI_POWER_CMD=${bmcinfo#*ipmi_power_cmd=}
    IPMI_POWER_CMD=${IPMI_POWER_CMD%%,*}

    ACCOUNT=${bmcinfo#*account=}
    ACCOUNT=${ACCOUNT%%,*}

    PASSWORD=${bmcinfo#*password=}
    PASSWORD=${PASSWORD%%,*}
}


# get details config info
if [ "$SERIALTYPE" = "telnet" -a "$POWERTYPE" = "PDU" ]; then
    check_pud_serial_config

elif [ "$SERIALTYPE" = "ipmi" -a "$POWERTYPE" = "BMC" ]; then
    check_bmc_config
fi










