#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#description: connect the UART port of user's board by telnet

USERCFG=/etc/boardlab/users.cfg
LABCFG=/etc/boardlab/boardlab.cfg
USERLOG=/var/log/login.log
BOARDCFG=/etc/boardlab/boards.cfg
PDUCFG=/etc/boardlab/pdu.cfg
BMCCFG=/etc/boardlab/bmc.cfg
SERIALCFG=/etc/boardlab/serial.cfg

USERNAME=`whoami`
. $LABCFG

# Check whether user in permit list
grep -w "$USERNAME:" $USERCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "You are not permited to use the board in OpenLab."
    exit 1
fi

# Get the board index
BOARDIDX=1
if [ $# -gt 0 ]; then
    if [ "$1" -gt 0 ] 2>/dev/null ; then
        BOARDIDX=$1
    fi
fi

userinfo=`grep -w "$USERNAME:" $USERCFG`
boards=${userinfo#*boards=}

if [ x"boardslist" = x"$1" ]; then
    echo "${USERNAME} possessed boards list:"
    echo "Idx: Board No -> Shared Users"
    idx=1
    while [ true ]
    do
	boardno=`echo ${boards%%,*} | cut -d " " -f$idx`
	if [ x"" = x"$boardno" ]; then
		exit 0
	fi
	shared=`grep -E "boards=.*\b${boardno}\b" $USERCFG | grep -v "${USERNAME}:" | cut -d "," -f1 | sed "s/email=//g" | tr '\n' ";"|sed "s/;/; /g"`
	if [ x"" = x"$shared" ]; then
		echo "${idx}  : ${boardno}"
	else
		echo "${idx}  : ${boardno} -> ${shared}"
	fi
	let idx=$idx+1
    done
fi


BOARDIDX=`echo ${boards%%,*} | cut -d " " -f$BOARDIDX`
if [ x"" = x"$BOARDIDX" ]; then
    echo "Error board index!"
    exit 1
fi


# Check whether the board is deployed
BOARDNUM="BOARD$BOARDIDX"
grep -w "$BOARDNUM:" $BOARDCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "$BOARDNUM is not deployed into Open Lab, please touch the Lab. manager."
    exit 1
fi


# Get the email of user
#eval PORT=$((PORT$index))
EMAIL=${userinfo#*email=}
EMAIL=${EMAIL%%,*}

# Get the board information
boardinfo=`grep -w "$BOARDNUM:" $BOARDCFG`
BOARDTYPE=${boardinfo#*boardtype=}
BOARDTYPE=${BOARDTYPE%%,*}

SERIALINFO=${boardinfo#*serialinfo=}
SERIALINFO=${SERIALINFO%%,*}
SERIALTYPE=`echo $SERIALINFO | sed 's/[0-9]*//g'`

GRUBFILE=${boardinfo#*mac=}
GRUBFILE=${GRUBFILE%%,*}
GRUBFILE=$ftp_dir/$grub_prefix"-"$GRUBFILE

POWERINFO=${boardinfo#*powerinfo=}
POWERINFO=${POWERINFO%%,*}
POWERINFO=`echo "$POWERINFO" | cut -d " " -f1`
OUTLEN=`echo "$POWERINFO" | cut -d " " -f2` 
POWERTYPE=`echo $POWERINFO | sed 's/[0-9]*//g'`











