#!/bin/bash
#author: Alan Huang, Justin Zhao
#date 12/10/2015
#description: connect the UART port of user's board by telnet

USERCFG=/etc/boardlab/users.cfg
USERLOG=/var/log/login.log
BOARDCFG=/etc/boardlab/boards.cfg
LABCFG=/etc/boardlab/boardlab.cfg

USERNAME=`whoami`
#. $BOARDCFG
. $LABCFG

# Check whether user in permit list
grep -w "$USERNAME:" $USERCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "You are not permited to use the board in OpenLab."
    exit 1
fi

# Get the board index
BOARDIDX=1
if [ $# -gt 0 ]; then
    if [ "$1" -gt 0 ] 2>/dev/null ; then
        BOARDIDX=$1
    fi
fi

userinfo=`grep -w "$USERNAME:" $USERCFG`
boards=${userinfo#*boards=}
BOARDIDX=`echo ${boards%%,*} | cut -d " " -f$BOARDIDX`
if [ x"" = x"$BOARDIDX" ]; then
    echo "Error board index!"
    exit 1
fi

# Check whether the board is deployed
grep -w "BOARD$BOARDIDX:" $BOARDCFG >/dev/null 2>&1
if [ $? != 0 ];then
    echo "Board$BOARDIDX is not deployed into Open Lab, please touch the Lab. manager."
    exit 1
fi

# Get the email of user
#eval PORT=$((PORT$index))
EMAIL=${userinfo#*email=}
EMAIL=${EMAIL%%,*}

# Get the board information
boardinfo=`grep -w "BOARD$BOARDIDX:" $BOARDCFG`
PORT=${boardinfo#*ser2net=}
PORT=${PORT%%,*}

BOARDTYPE=${boardinfo#*type=}
BOARDTYPE=${BOARDTYPE%%,*}
