#!/bin/bash
if [ $# != 1 ] ;then
    echo "      Usage: $0 port"
    echo "      You must specify the port num, an example is:"
    echo "      connect 20045 "
    exit
fi
USERLIST=/home/htsat/userlist
USERLOG=/var/log/login.log
#echo "Welcome To Use D02 Board"
check_use ()
{
    ps -ef |grep telnet |grep $PORT
    if [ $? != 0 ];then 
        return 0 #没有被使用
     else
        return 1   #已经被使用
     fi
}
USERNAME=$1
# verify_user and get the email and port number
grep "$USERNAME" $USERLIST >/dev/null 2>&1
if [ $? != 0 ];then
    echo "  Invalid Username, please confirm"
    exit 1
fi
EMAIL=`grep $USERNAME $USERLIST |cut -d " " -f2`
PORT=`grep $USERNAME $USERLIST |cut -d " " -f3`

#check whether the under using 
ps -ef |grep telnet |grep $PORT >/dev/null 2>&1
if [ $? = 0 ] ;then
    last_user=`grep $PORT $USERLOG | tail -n 1 | cut -d " " -f2`
    echo "  $last_user is using the board now "
    echo "  if you really want to use it, please contact with him"
    exit 1
fi
#grep "$name $mail" $USERLIST >/dev/null 2>&1 
#    if [ $? != 0 ] ;then
#        echo "  Sorry $name, You are not permit to use the board "
#        exit
#    else
#        echo "  Hello $name, Welcome To Use D02 Board"
#    fi
echo "User $EMAIL login port $PORT at `date`">> $USERLOG
telnet localhost $PORT 
